# Generated by Django 2.0.7 on 2018-08-26 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_structure', models.CharField(help_text='Description of pricing structure', max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('price', models.PositiveIntegerField(default=0, help_text='Product price in cents')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='products.Product'),
        ),
    ]
