# Generated by Django 2.0.7 on 2018-08-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180826_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
